package com.example.travel.agent;

import com.example.travel.config.TravelModelsProperties.AgentRole;
import com.example.travel.graph.TravelState;
import com.example.travel.graph.model.PlannerExtraction;
import com.example.travel.service.RoutedLlm;
import com.example.travel.support.JsonSupport;
import com.example.travel.support.TripSlotHeuristics;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

@Service
public class PlannerAgentService {

    private static final Logger log = LoggerFactory.getLogger(PlannerAgentService.class);
    private static final Pattern ROUTE = Pattern.compile(
            "(?i)\\bfrom\\s+(.+?)\\s+to\\s+(.+?)(?:\\s+for\\s+|\\s+on\\s+|\\s+today\\b|[.!?]|$)");

    private final RoutedLlm routedLlm;
    private final JsonSupport jsonSupport;

    public PlannerAgentService(RoutedLlm routedLlm, JsonSupport jsonSupport) {
        this.routedLlm = routedLlm;
        this.jsonSupport = jsonSupport;
    }

    public Map<String, Object> plan(TravelState state) {
        log.info("Planner agent extracting trip slots from user request");
        String content;
        try {
            content = routedLlm.complete(AgentRole.PLANNER,
                    "You are the Planner Agent. Extract trip slots from the CURRENT REQUEST only. "
                            + "Ignore conflicting destinations in conversation history. Return JSON only: "
                            + "{\"origin\":\"\",\"destination\":\"\",\"departureDate\":\"yyyy-MM-dd\","
                            + "\"returnDate\":\"yyyy-MM-dd\",\"travelers\":1,\"budget\":\"\",\"hotelBudget\":\"\",\"travelStyle\":\"\"}. "
                            + "For country-only destinations like Japan, set destination to the main city (Tokyo). "
                            + "Preserve overall trip budgets like '2 lakh' or '₹200000'. Use empty strings when unknown. If a monetary ceiling is scoped to hotels, put it in hotelBudget and leave budget empty. Do not turn a hotel price ceiling into the overall trip budget. "
                            + "For departureDate and returnDate, return a value ONLY when the CURRENT REQUEST explicitly provides a calendar date. "
                            + "A duration such as '7 days' is not a calendar date; leave both date fields empty. Never use today's date as an answer to a missing date. "
                            + "Never invent London/LHR unless the user said London. "
                            + "Do not call external tools. Airport/IATA resolution is handled by the graph after slot extraction.",
                    "CURRENT REQUEST: " + state.userRequest()
                            + "\nKnown origin: " + state.origin()
                            + "\nKnown destination: " + state.destination()
                            + "\nDeparture date: " + state.departureDate()
                            + "\nReturn date: " + state.returnDate()
                            + "\nTravelers: " + state.travelers()
                            + "\nBudget: " + state.budgetLabel()
                            + "\nStyle: " + state.travelStyle()
                            + "\nHistory (background only): " + state.historyContext());
        } catch (Exception exception) {
            if (exception instanceof com.example.travel.exception.GraphStopRequestedException stop) throw stop;
            log.warn("Planner LLM extraction failed, using request fields and regex", exception);
            content = "";
        }

        PlannerExtraction extraction = jsonSupport.read(content, PlannerExtraction.class).orElse(null);
        String origin = first(extraction == null ? null : extraction.getOrigin(),
                routeGroup(state.userRequest(), 1),
                state.origin(),
                state.preferredAirport());
        // The current request has already passed through the query normalization
        // capability, so its destination hint is the canonicalized current-turn value.
        String requestDestinationHint = TripSlotHeuristics.extractDestinationHint(state.userRequest());
        String destinationCandidate = first(requestDestinationHint,
                extraction == null ? null : extraction.getDestination(),
                routeGroup(state.userRequest(), 2),
                state.destination());
        final String destination = TripSlotHeuristics.normalizePlace(destinationCandidate);
        origin = TripSlotHeuristics.normalizePlace(origin);
        // Dates are resolved deterministically before the planner runs. The planner LLM
        // must never overwrite the authoritative current-turn dates with a date copied
        // from conversation history or generated by the model. This is especially
        // important for live flight searches where a one-day-old date must not reach
        // the MCP provider.
        boolean currentTurnHasDateHint = TripSlotHeuristics.hasDateHint(state.userRequest())
                || TripSlotHeuristics.hasDurationHint(state.userRequest());
        LocalDate departure = state.departureDate();
        LocalDate returning = state.returnDate();
        if (departure.isBefore(LocalDate.now()) && !currentTurnHasDateHint) {
            departure = LocalDate.now();
            if (returning.isBefore(departure)) {
                returning = departure.plusDays(5);
            }
        }
        // A duration/date inference is useful only for a genuine journey workflow.
        // Specialist lookups such as hotel search must not manufacture a trip window.
        if ("TRIP_PLANNING".equalsIgnoreCase(state.requestType()) || state.needsItinerary()
                || state.needsFlights() || state.needsWeather()) {
            returning = TripSlotHeuristics.inferReturnDate(state.userRequest(), departure, returning);
        }

        int travelers = extraction != null && extraction.getTravelers() != null
                ? Math.max(extraction.getTravelers(), 1)
                : state.travelers();
        String extractedHotelBudgetLabel = extraction == null ? null : extraction.getHotelBudget();
        BigDecimal hotelBudget = TravelState.parseBudget(extractedHotelBudgetLabel);

        // The semantic intent agent owns capability selection. Planner only maps
        // scoped monetary constraints into the correct state field. A hotel ceiling
        // must never become the overall trip budget.
        String budgetLabel;
        if (state.needsBudget() || "TRIP_PLANNING".equalsIgnoreCase(state.requestType())) {
            budgetLabel = first(extraction == null ? null : extraction.getBudget(),
                    TripSlotHeuristics.extractBudgetLabel(state.userRequest()),
                    state.budgetLabel());
        } else {
            budgetLabel = state.budgetLabel();
        }
        String travelStyle = first(extraction == null ? null : extraction.getTravelStyle(), state.travelStyle());
        BigDecimal budget = TravelState.parseBudget(budgetLabel);
        if (budget == null) {
            budget = state.budget();
        }
        if (budget == null) {
            budget = TravelState.UNSET_BUDGET;
        }

        log.info("Planner resolved origin={}, destination={}, dates={} to {}, budget={}",
                origin, destination, departure, returning, budgetLabel);

        Map<String, Object> updates = new LinkedHashMap<>();
        updates.put(TravelState.ORIGIN, origin);
        updates.put(TravelState.DESTINATION, destination);
        updates.put(TravelState.DEPARTURE_DATE, departure);
        updates.put(TravelState.RETURN_DATE, returning);
        updates.put(TravelState.TRAVELERS, travelers);
        updates.put(TravelState.BUDGET_LABEL, budgetLabel);
        updates.put(TravelState.BUDGET, budget);
        if (hotelBudget != null) {
            updates.put(TravelState.HOTEL_BUDGET, hotelBudget);
        }
        updates.put(TravelState.TRAVEL_STYLE, travelStyle);
        updates.put(TravelState.DATES_FLEXIBLE, !TripSlotHeuristics.hasDateHint(state.userRequest()));
        updates.put(TravelState.ROUND_TRIP, state.roundTrip());
        updates.put(TravelState.LAST_DECISION, new com.example.travel.model.AgentDecision(
                "planner",
                state.requestType(),
                "slots origin=" + origin + " dest=" + destination + " strategy=" + state.planStrategy(),
                0.9));
        return updates;
    }

    private String routeGroup(String request, int group) {
        Matcher matcher = ROUTE.matcher(request == null ? "" : request);
        if (matcher.find()) {
            return matcher.group(group).trim().replaceFirst("[.!?].*$", "");
        }
        return "";
    }

    private String first(String... values) {
        return TravelState.firstNonBlank(values);
    }
}
