package com.example.travel.observability;

import io.micrometer.core.instrument.Counter;
import io.micrometer.core.instrument.MeterRegistry;
import io.micrometer.core.instrument.Timer;
import org.springframework.stereotype.Service;

import java.time.Duration;
import java.util.concurrent.atomic.AtomicInteger;

/**
 * Central metrics facade for agent execution.
 *
 * <p>Only low-cardinality dimensions are used as metric tags. User ids,
 * thread ids, prompts, arguments and error messages must stay out of metric
 * labels; those belong in structured logs/traces.</p>
 */
@Service
public class AgentObservabilityService {

    private final MeterRegistry registry;

    public AgentObservabilityService(MeterRegistry registry) {
        this.registry = registry;
    }

    public void recordLlmCall(String operation, String model, int inputTokens,
                              int outputTokens, long durationMs, boolean success) {
        String safeOperation = normalize(operation);
        String safeModel = normalize(model);

        Counter.builder("agent.llm.calls")
                .description("LLM calls made by the agent")
                .tag("operation", safeOperation)
                .tag("model", safeModel)
                .tag("status", success ? "success" : "error")
                .register(registry)
                .increment();

        Counter.builder("agent.llm.tokens.input")
                .description("Input tokens consumed by LLM calls")
                .tag("operation", safeOperation)
                .tag("model", safeModel)
                .register(registry)
                .increment(Math.max(0, inputTokens));

        Counter.builder("agent.llm.tokens.output")
                .description("Output tokens generated by LLM calls")
                .tag("operation", safeOperation)
                .tag("model", safeModel)
                .register(registry)
                .increment(Math.max(0, outputTokens));

        Timer.builder("agent.llm.duration")
                .description("LLM call duration")
                .tag("operation", safeOperation)
                .tag("model", safeModel)
                .register(registry)
                .record(Duration.ofMillis(Math.max(0, durationMs)));
    }

    public void recordLlmBudgetExhausted(String operation) {
        Counter.builder("agent.llm.budget.exhausted")
                .description("LLM execution budget exhaustion events")
                .tag("operation", normalize(operation))
                .register(registry)
                .increment();
    }

    public void recordMcpCall(String tool, long durationMs, boolean success, int attempt) {
        String safeTool = normalize(tool);

        Counter.builder("agent.mcp.calls")
                .description("MCP tool invocations")
                .tag("tool", safeTool)
                .tag("status", success ? "success" : "error")
                .register(registry)
                .increment();

        Timer.builder("agent.mcp.duration")
                .description("MCP tool invocation duration")
                .tag("tool", safeTool)
                .register(registry)
                .record(Duration.ofMillis(Math.max(0, durationMs)));

        if (attempt > 1) {
            Counter.builder("agent.mcp.retries")
                    .description("MCP retry attempts")
                    .tag("tool", safeTool)
                    .register(registry)
                    .increment();
        }
    }

    public void recordMcpPolicyDecision(String tool, String decision) {
        Counter.builder("agent.mcp.policy.decisions")
                .description("MCP governance decisions")
                .tag("tool", normalize(tool))
                .tag("decision", normalize(decision))
                .register(registry)
                .increment();
    }

    public void recordRetry(String category, String reason) {
        Counter.builder("agent.retries")
                .description("Agent and provider retry attempts")
                .tag("category", normalize(category))
                .tag("reason", normalize(reason))
                .register(registry)
                .increment();
    }

    public void recordReplan(String reason) {
        Counter.builder("agent.replans")
                .description("Agent replans")
                .tag("reason", normalize(reason))
                .register(registry)
                .increment();
    }

    public void recordNode(String node, long durationMs, boolean success) {
        Counter.builder("agent.nodes")
                .description("Agent graph node executions")
                .tag("node", normalize(node))
                .tag("status", success ? "success" : "error")
                .register(registry)
                .increment();

        Timer.builder("agent.node.duration")
                .description("Agent graph node duration")
                .tag("node", normalize(node))
                .register(registry)
                .record(Duration.ofMillis(Math.max(0, durationMs)));
    }

    public void recordProviderCall(String provider, String operation, long durationMs, boolean success) {
        Counter.builder("agent.provider.calls")
                .description("External provider calls")
                .tag("provider", normalize(provider))
                .tag("operation", normalize(operation))
                .tag("status", success ? "success" : "error")
                .register(registry)
                .increment();

        Timer.builder("agent.provider.duration")
                .description("External provider call duration")
                .tag("provider", normalize(provider))
                .tag("operation", normalize(operation))
                .register(registry)
                .record(Duration.ofMillis(Math.max(0, durationMs)));
    }

    public void recordGoalOutcome(String outcome) {
        Counter.builder("agent.goal.outcomes")
                .description("Agent goal outcomes")
                .tag("outcome", normalize(outcome))
                .register(registry)
                .increment();
    }

    public void recordRun(String status, long durationMs) {
        Counter.builder("agent.runs")
                .description("Agent runs")
                .tag("status", normalize(status))
                .register(registry)
                .increment();

        Timer.builder("agent.run.duration")
                .description("End-to-end agent run duration")
                .register(registry)
                .record(Duration.ofMillis(Math.max(0, durationMs)));
    }

    private static String normalize(String value) {
        if (value == null || value.isBlank()) return "unknown";
        return value.trim().toLowerCase()
                .replaceAll("[^a-z0-9_.-]", "_");
    }
}
